# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\QQBots\JianerSetupWizard\UI\JianerSetupApply.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(820, 675)
        Form.setMinimumSize(QtCore.QSize(650, 465))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PopUpAniStackedWidget = PopUpAniStackedWidget(Form)
        self.PopUpAniStackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.PopUpAniStackedWidget.setObjectName("PopUpAniStackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LargeTitleLabel = LargeTitleLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(30)
        font.setBold(False)
        self.LargeTitleLabel.setFont(font)
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")
        self.horizontalLayout_2.addWidget(self.LargeTitleLabel)
        self.verticalLayout.addWidget(self.widget)
        self.SubtitleLabel_5 = SubtitleLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC Medium")
        font.setPointSize(14)
        font.setBold(False)
        self.SubtitleLabel_5.setFont(font)
        self.SubtitleLabel_5.setWordWrap(True)
        self.SubtitleLabel_5.setObjectName("SubtitleLabel_5")
        self.verticalLayout.addWidget(self.SubtitleLabel_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.SmoothScrollArea = SmoothScrollArea(self.page)
        self.SmoothScrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 455))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.PrimaryPushButton = PrimaryPushButton(self.scrollAreaWidgetContents)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.gridLayout.addWidget(self.PrimaryPushButton, 1, 0, 1, 1)
        self.PlainTextEdit = PlainTextEdit(self.scrollAreaWidgetContents)
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.PlainTextEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.PlainTextEdit, 0, 0, 1, 1)
        self.PrimaryPushButton_2 = PrimaryPushButton(self.scrollAreaWidgetContents)
        self.PrimaryPushButton_2.setObjectName("PrimaryPushButton_2")
        self.gridLayout.addWidget(self.PrimaryPushButton_2, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.SmoothScrollArea)
        self.PopUpAniStackedWidget.addWidget(self.page)
        self.horizontalLayout.addWidget(self.PopUpAniStackedWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "简儿 - 核对设置清单"))
        self.LargeTitleLabel.setText(_translate("Form", "核对设置清单并生成设置"))
        self.SubtitleLabel_5.setText(_translate("Form", "    根据您的设置，当前已生成如下设置内容："))
        self.PrimaryPushButton.setText(_translate("Form", "应用"))
        self.PrimaryPushButton_2.setText(_translate("Form", "      启动吧，我的简儿！"))
from qfluentwidgets import ElevatedCardWidget, IconWidget, LargeTitleLabel, PopUpAniStackedWidget, SmoothScrollArea, SubtitleLabel, TitleLabel, FluentIcon, CardWidget, LineEdit, PlainTextEdit, PrimaryPushButton
from wizardWindows import JianerSetupWizard_rc